feat: dispose & init controller, deal with audio session
pagecall/pagecall-ios-sdk pull request #10
Opened 2023-02-06 03:04 UTC by parkjurung

- coreapp 에서 ChimeController 를 dispose 할 수 있습니다.
- coreapp 에서 ChimeController 를 init 할 수 있습니다. (initController)
- audioSession.setCategory 에 추가적인 옵션을 부여합니다. 안정적인 음성 송수신을 보장할 것으로 기대합니다.
- AudioSessionRouteChange 될 때 마다 audioSession.setCategory를 새로 해주고 coreapp에 로그를 전달합니다.

테스트

pagecall-ios 앱에 적용하여 테스트 완료

2023-02-06 03:05 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +    case createSession, initController, start, stop, getPermissions, requestPermission, pauseAudio, resumeAudio, getAudioDevices, setAudioDevice, requestAudioVolume, dispose
"init"은 사용할 수 없는 예약어라서 "initController" 를 대신 사용했습니다.

2023-02-06 03:30 UTC, lockcept approved these changes

2023-02-06 03:45 UTC, parkjurung commented
더 일반화한 후에 다시 리뷰 요청하겠습니다.

2023-02-06 09:53 UTC, parkjurung commented
handleInterrupt 까지 하고 다시 열겠습니다.

2023-02-07 05:04 UTC, lockcept approved these changes

2023-02-07 05:50 UTC, js-seo requested changes

2023-02-07 05:50 UTC, js-seo commented on Sources/PagecallSDK/NativeBridge.swift
> +    case createSession, initController, start, stop, getPermissions, requestPermission, pauseAudio, resumeAudio, getAudioDevices, setAudioDevice, requestAudioVolume, dispose
[Optional]
```suggestion
    case createSession, `init`, start, stop, getPermissions, requestPermission, pauseAudio, resumeAudio, getAudioDevices, setAudioDevice, requestAudioVolume, dispose
```

이렇게 가능할것 같아요
https://stackoverflow.com/a/31315650

2023-02-07 05:50 UTC, js-seo commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.response(requestId: requestId)
[Major]
하위호환성 때문에 74줄을 그대로 두신 것 같은데,
이걸 호출하는 신 코어앱 + 이게 아직 없는 구 SDK가 있으면 ChimeController가 중복생성되지 않을까요?

2023-02-07 05:57 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.response(requestId: requestId)
아래와 같은 순서를 생각했습니다.

1. 모든 사용사례에서 init/dispose가 노출된 SDK 가 쓰이도록 함
2. 코어앱을 수정하여 refresh(문제해결)할때 dispose 후 init 하도록 함. 정상 상황에서는 init을 명시적으로 부를 일이 없음

즉, 코어앱에서는 앞으로도 항상 묵시적으로 최초 컨트롤러가 생성되고 명시적 init은 항상 dispose 후 하는 것으로 생각했습니다.

컨트롤러 초기화가 자동으로도 되고, 명시적으로도 되는 점이 신경쓰였으나 더 좋은 방법을 떠올리지 못했습니다.

2023-02-07 06:05 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.response(requestId: requestId)
init 이라는 이름을 initAgain, reinit 또는 revive 등으로 바꾸는 것은 어떤가요? 그 목적에 맞도록

2023-02-07 06:32 UTC, js-seo commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.response(requestId: requestId)
그렇군용
dispose가 안된 상태로 init 을 쓰면 문제가 있는 상태에 빠질 수 있는데, 이 사용법이 코드 바깥에 존재하는게 아쉽네요
chimeController가 dispose 되어있지 않으면 오류 응답을 주는게 좋을것 같아요
그리고 dispose된 경우 chimeController를 nil로 비워줘야 GC가 될 것 같아요
이름은 init 도 나쁘지 않은 것 같고,
한편으로 웹뷰 여러개 떴을때 어떤 액션(ex. 입장버튼 누르기)이 init을 촉발한다면 ChimeController가 여러개 생기는 일을 막을 수 있어서 init을 명시적으로 해주게 하는것도 괜찮다고 보았어요

2023-02-07 06:36 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.response(requestId: requestId)
변경 요청의 핵심이 "chimeController가 dispose 되어있지 않으면 오류 응답을 주는게 좋을것 같아요" 이거 였다는 사실을 방금 눈치챘습니다.

그렇다면 우선 case .`init` 에서 disposed 여부 (self.chimeController nil 여부) 체크하고 nil 일 경우에만 새로 init 해주고 아닐 경우에는 response error 하도록 변경하면 목적에 부합할까요?

2023-02-07 08:24 UTC, js-seo commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.response(requestId: requestId)
넵~!

2023-02-07 08:30 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.response(requestId: requestId)
[fix: check if prev controller exists before init new one](https://github.com/pagecall/pagecall-ios-sdk/pull/10/commits/797de065b64876f26f86c17e489be01023875592) 확인부탁드립니다!

2023-02-07 09:18 UTC, js-seo approved these changes

2023-02-07 09:18 UTC, js-seo commented on Sources/PagecallSDK/NativeBridge.swift
> +                }
[Optional]
[Optional binding](https://velog.io/@wook4506/iOS-Swift-%EC%98%B5%EC%85%94%EB%84%90-%EB%B0%94%EC%9D%B8%EB%94%A9-Optional-Binding) 을 이용해 더 swift 스럽게 짜기 (`?` 를 최소화하여 실수할 여지를 줄입니다)

```suggestion
            if bridgeAction == .`init` {
                if let _ = chimeController {
                    self.response(requestId: requestId, errorMessage: "ChimeController already exists")
                } else {
                    self.chimeController = .init(emitter: self.emitter)
                    self.response(requestId: requestId)
                }
            } else if let chimeController = chimeController {
              switch bridgeAction {
                case .start:
                  chimeController.start { ... }
                ...
              }
            } else {
                self.response(requestId: requestId, errorMessage: "ChimeController does not exist")
            }
```

2023-02-07 09:18 UTC, js-seo commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.emitter.log(name: "ChimeController", message: "dispose success")
[Optional]
```suggestion
                self.emitter.log(name: "ChimeController", message: "dispose success")
                self.chimeController = nil;
```

2023-02-07 09:43 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +                self.emitter.log(name: "ChimeController", message: "dispose success")
[fix: use optional binding](https://github.com/pagecall/pagecall-ios-sdk/pull/10/commits/193bae9cd4477b88626edb8424c7dc0bd81e67ba)

2023-02-07 09:43 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +                }
[fix: use optional binding](https://github.com/pagecall/pagecall-ios-sdk/pull/10/commits/193bae9cd4477b88626edb8424c7dc0bd81e67ba)

2023-02-08 02:06 UTC, js-seo approved these changes

2023-02-08 02:06 UTC, merged