feat: uikit example
pagecall/pagecall-ios-sdk pull request #49
Opened 2023-07-23 06:35 UTC by qqq1130

uikit example 초안입니다.
현재는 항상 roomId와 token이 주어진다고 가정하고 만들었습니다.
또한, 디버깅용 query string들은 고객사에서 활용할 내용은 아니니 항상 valid한 형태로 입력된다고 가정했습니다.

https://github.com/pagecall/pagecall-ios-sdk/assets/106307725/1a5ca5fb-20a7-4a4a-9c75-08d02029cadf

https://github.com/pagecall/pagecall-ios-sdk/assets/106307725/4d1b246b-c968-496a-9895-8379c7b0cde7

2023-08-01 04:17 UTC, js-seo requested changes
전반적으로 깔끔하네요!

2023-08-01 04:17 UTC, js-seo commented on examples/uikit/UIKit Example/Helpers/Alert.swift
> +        label.attributedText = NSMutableAttributedString(string: "입력 값이 필요합니다.", attributes: [NSAttributedString.Key.paragraphStyle: paragraphStyle])
유저가 접하는 모든 문자열은 영문으로 통일부탁드립니다!

2023-08-01 04:17 UTC, js-seo commented on examples/uikit/UIKit Example/SceneDelegate.swift
> +        guard let scene = scene as? UIWindowScene else { return }
처음에 Storyboard로 초기화된 프로젝트이다보니 `Main.storyboard` 등 안 쓰게 된 관련 파일을 다 정리해주는 것이 필요할 것 같습니다~!

2023-08-01 04:23 UTC, js-seo requested changes

2023-08-01 04:23 UTC, js-seo commented on examples/uikit/UIKit Example/Helpers/SendMessage.swift
> +        self.pagecallWebView = pagecallWebView
[Minor]
얘가 필요한 건 sendMessage 함수 뿐인데 너무 많은 것을 넘겨받은 것 같습니다
함수만 넘겨주거나 이 안에서 쓰는 것은 타입으로 제한하는 등 더 좁힐 필요가 있을 것 같네요
(뭐가 best practice 인지는 저도 잘 모르겠어요)

```swift
  init(sendMessage: @escaping (String) -> Void) {
    ...
  }
```

```swift
protocol SendMessageDelegate {
  func sendMessage(message: String)
} 

...
  init(delegate: SendMessageDelegate) {
...
```

2023-08-01 07:24 UTC, qqq1130 commented on examples/uikit/UIKit Example/Helpers/Alert.swift
> +        label.attributedText = NSMutableAttributedString(string: "입력 값이 필요합니다.", attributes: [NSAttributedString.Key.paragraphStyle: paragraphStyle])
[691547a](https://github.com/pagecall/pagecall-ios-sdk/pull/49/commits/691547a73009b7b34012df71c667284cd1c62a6c)

2023-08-01 07:24 UTC, qqq1130 commented on examples/uikit/UIKit Example/SceneDelegate.swift
> +        guard let scene = scene as? UIWindowScene else { return }
[42d5bf4](https://github.com/pagecall/pagecall-ios-sdk/pull/49/commits/42d5bf4aad4497b82e3a6470435bdd742b156ded)

2023-08-01 07:24 UTC, qqq1130 commented on examples/uikit/UIKit Example/Helpers/SendMessage.swift
> +        self.pagecallWebView = pagecallWebView
[6e11ada](https://github.com/pagecall/pagecall-ios-sdk/pull/49/commits/6e11adac4fa30c9c21e7b2ef6b6b337ecd5113ce)

2023-08-07 03:23 UTC, js-seo approved these changes
좋습니다!

2023-08-07 03:23 UTC, js-seo commented on examples/uikit/UIKit Example/Info.plist
> +</string>
[Optional]
```suggestion
	<string>Microphone permission is required.</string>
```

2023-08-07 03:38 UTC, qqq1130 commented on examples/uikit/UIKit Example/Info.plist
> +</string>
@js-seo  반영했습니다!

2023-08-07 03:41 UTC, merged