feat: swiftui sample app
pagecall/pagecall-ios-sdk pull request #51
Opened 2023-07-27 07:17 UTC by qqq1130

swiftui 샘플 앱입니다.
query 파싱 로직의 경우, 디버깅용이기 때문에 항상 옳은 형식의 입력만 들어온다고 가정했습니다

https://github.com/pagecall/pagecall-ios-sdk/assets/106307725/0a2da04d-110b-4cd0-aa30-e4c907d771db

2023-08-01 04:27 UTC, js-seo requested changes

2023-08-01 04:27 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/SendMessage.swift
> +    init( pagecallWebView: PagecallWebView, isSendingMessage: Binding<Bool>, message: Binding<String>) {
[Minor]
https://github.com/pagecall/pagecall-ios-sdk/pull/49#discussion_r1280093859 랑 동일

2023-08-01 04:27 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/Pagecall.swift
> +        (pagecallWebView.delegate as? PagecallManager)?.setHandlers(onLoad: onLoad, onTerminate: onTerminate, onReceive: onReceive)
[Minor]
어딘가에서 `pagecallWebView.delegate`를 `PagecallManager`로 설정해준다는, 이 파일 바깥의 사실을 알고 있는 코드입니다 이런 패턴은 각 클래스가 하나의 역할만을 한다는 전제를 깨기 때문에 한 부분을 수정할 때 그 부분에만 집중할 수 있는 것이 아니라 모든 부분의 동작을 염두에 두도록 만듭니다
더 나은 구조가 없을까요?

2023-08-01 09:14 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/Pagecall.swift
> +        (pagecallWebView.delegate as? PagecallManager)?.setHandlers(onLoad: onLoad, onTerminate: onTerminate, onReceive: onReceive)
[52e20a2](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/52e20a25e9814c7bb12c7ce22dd59391382f12dc)

2023-08-01 09:14 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/SendMessage.swift
> +    init( pagecallWebView: PagecallWebView, isSendingMessage: Binding<Bool>, message: Binding<String>) {
[37be3d3](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/37be3d3719b2c38945865aea238c951aa3c98880)

2023-08-02 01:38 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/Pagecall.swift
> +        (pagecallWebView.delegate as? PagecallManager)?.setHandlers(onLoad: onLoad, onTerminate: onTerminate, onReceive: onReceive)
@js-seo 여기서 '각 클래스가 하나의 역할만을 한다는 전제를 깬다'는 말은 `Pagecall`의 객체가 `PagecallWebView`를 보여주는 역할뿐 아니라 `PagecallWebView`의 delegate을 `PagecallManager`로 캐스팅하는 역할까지 하게 된다는 의미인가요?

2023-08-07 03:40 UTC, js-seo requested changes

2023-08-07 03:40 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/Loading.swift
> +    @Binding var isShowingLoading: Bool
[Minor]
이 값을 바깥에서 전달해줄 필요가 있을까요? `isLoading` 값에 따라서 내부에서 알아서 처리할 수 있게 할 수 없을까요?
그리고 isLoading 의 값을 안에서 조작하지 않는데 그렇다면 Binding이 아니라 일반 var로 전달하는 것으로 충분하지 않나요?

2023-08-07 03:40 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/SendMessage.swift
> +    @Binding var isSendingMessage: Bool
[Minor]
전반적으로 Binding 을 많이 사용하셨는데, Binding은 상태를 부모와 자식이 같이 조작할 수 있기 때문에 이해하기가 더 어려워지는 것 같습니다.
1\) 자식도 그 상태를 조작해야 하는 경우, 2) 애니메이션 등의 이유로 불가피한 경우가 아니면 일방향적으로 상태를 전달하는 방법을 찾아보시면 좋겠습니다

2023-08-07 03:40 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/Pagecall.swift
> +        (pagecallWebView.delegate as? PagecallManager)?.setHandlers(onLoad: onLoad, onTerminate: onTerminate, onReceive: onReceive)
아니오 '캐스팅'과 같은 것은 명령이자 동작이지 역할이라고 볼 수 없습니다
역할은 코드라인으로 나타나는게 아니라 이 클래스, 컴포넌트, 파일 등이 뭘 하는 것인지 자연어 한문장으로 나타낼 수 있는, 심리적으로 존재하는 모델입니다
interface와 implementation의 분리에 대한 개념을 들어보셨을텐데요 
한번 쓰고 버릴 코드가 아니라면 어떻게든 결과를 만들려고 하기보다 인터페이스 중심으로 사고하셔야 합니다
Pagecall, PagecallManager, PagecallView 등의 역할이 분명히 보이지가 않습니다

'이게 필요하니까 이것도 하고 저것도 하고'가 아니라 '이 클래스는 무엇을 하는 친구이다 그러니까 이런걸 넣어줘야겠다' 가 되어야 합니다
이 코드에서 드러나는 사고과정은 '이 코드는 handler를 달아줘야 하니까 저걸 꺼내서 써야되겠다 그리고 그걸 꺼내서 쓰려면 이걸 넣어줘야겠구나' 입니다 이렇게 역할을 정의하지 않고 짜게 되면 이해하기도 어렵고 그래서 문제가 생기기가 쉽고 그때 디버깅하기도 어렵습니다

2023-08-07 03:40 UTC, js-seo commented on examples/swiftui/SwiftUI Example/PagecallView.swift
> +                    pagecallWebView: pagecallWebView,
[Minor]
SwiftUI View를 위해 UIKit의 View를 생성해서 넣어주는 패턴이 어색합니다 꼭 이렇게 해야할까요?
PagecallWebView가 재생성되는 문제를 해결하려는 시도인 것은 인지하고 있습니다 그런데 더 좋은 방법을 찾아보셨으면 좋겠네요

2023-08-07 05:47 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/Loading.swift
> +    @Binding var isShowingLoading: Bool
isShowingLoading 값은 바깥에서 전달 안해줘도 되는데 제가 리팩토링 과정에서 놓쳐서 수정해뒀습니다!
isLoading값은 안에서 조작하지 않는다 해도 isLoading값을 구독하고 있다가 값이 바꼈을 때 progress bar의 progress를 수정해줘야하기 때문에 @Binding으로 받아야합니다! 
실험해봤는데 그냥 boolean var로 받고 .onAppear 등으로 progress bar의 상태에 반영하려 하면 isLoading값이 바뀌어도 Loading 뷰가 리렌더링이 안 되어서 코드가 실행되지 않습니다.

2023-08-07 05:48 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/Loading.swift
> +    @Binding var isShowingLoading: Bool
[2afcf8b](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/2afcf8b464f468295c2e36bec220ec0981c73c94)

2023-08-07 06:27 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/SendMessage.swift
> +    @Binding var isSendingMessage: Bool
[14b2e35](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/14b2e35121b5acf6b2a9380ad27cd6cfc4122032)

여기 말고는 Binding이 필요하다고 판단했습니다 ㅜㅜ

2023-08-08 09:39 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/PagecallView.swift
> +                    pagecallWebView: pagecallWebView,
[b63fbba](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/b63fbbaf9b9dce669122e5085fadb04e76730215)

주요 변경사항은 다음과 같습니다.
(변경사항이 확정되고 나면 원래의 PR에도 구조에 대한 설명을 추가해두겠습니다.)

- `RoomView`: 로딩화면, 페이지콜 룸, 메시지 보내기 등 전반적인 미팅룸에서 필요한 화면들
- `PagecallWebViewWrapper`: PagecallWebView를 감싸고 있는 UIView로, PagecallDelegate으로서의 역할을 합니다. (일반적인 swiftUI의 view들은 class가 아닌 struct 이기에 PagecallDelegate으로서 작동할 수 없기 때문에 필요합니다)
- `PagecallBridge`: UIKit의 UIView인 PagecallWebViewWrapper가 SwiftUI의 View로 쓰일 수 있게 만드는 역할.

2023-08-12 05:49 UTC, qqq1130 commented
@js-seo 
[3c66953](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/3c6695350b3d9a0cc6b33c62d72f29b1c9a52b86), [14f5523](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/14f5523f458330a53d5c42cd45c549b793d9bc83), [9f65b2d](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/9f65b2d76810f3857d0b49adb8edc0fc8c188522),[5d9523e](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/5d9523ee987b63b9c18b0afd6c0b07c71c43a09b) : 각각 @Binding의 사용을 없앴습니다. 목적은 각 뷰들의 행동의 범위를 최대한 제약하고 부모 뷰에서 각 자식뷰들이 보일지 말지, 자식뷰의 특정 이너뷰가 탭 되었을 때 어떤 행동을 할지를 조작하는 것입니다.
<br>
[f3fd06c](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/f3fd06cbc6e0d750d2afc135185d235d5f71a3f7):
제리가 일대일 과외해주신 내용 반영한 것입니다.
<br>
[aae0780](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/aae0780022732ce93f43c4b8c26a6c4144d75c63): NavigationLink의 사용을 좀 더 직관적이고 선언적으로 바꿨습니다. 기존에는 버튼따로, 링크따로 였는데 버튼에 링크를 바로 연결했고, HomeView와 RoomView 사이의 @Binding을 없앴습니다. 이렇게 해서 RoomView에서 마음대로 자기자신을 보이게 하는 등의 행동을 할 수 없습니다. 또 HomeView에서도 코드를 통해서는 RoomView를 마음대로 보이게/보이지 않게 할 수 없고 오로지 NavigationLink만을 통해서 그렇게 할 수 있습니다. 
<br>
[8e67a13](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/8e67a13a4bb6a09bb89640a65fbf8695912e0ff8): roomId가 입력되었는지 입력되지 않았는지 등을 판단할 때 '==""' 가 아닌 isEmpty를 사용하도록 변경한 것입니다.

2023-08-16 04:13 UTC, js-seo requested changes

2023-08-16 04:13 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/Loading.swift
> +    @State private var progress = Double(0)
[Major]
progress가 25%까지만 차게될 것 같은데 의도일까요?

2023-08-16 04:13 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/ProgressBar.swift
> +                    .offset(x: min(geo.size.width, geo.size.width * progress) - 10, y: 0)
[Optional]
L35의 Rectangle과 묶어서 더 간단하고 표현력 있게 (프로그레스가 차오르는 네모와 연필모양이 같이 간다는 걸 이해하기 쉽게) 할 수 있는 방법이 있을 것 같네요

2023-08-16 04:13 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/SendMessage.swift
> +@available(iOS 15.0, *)
[Minor]
이거 다 빼고 SwiftUI 프로젝트 자체의 타겟 버전을 15 이상으로 변경해주세요

2023-08-16 04:13 UTC, js-seo commented on examples/swiftui/SwiftUI Example/HomeView.swift
> +    private func parseQueryItems() -> [URLQueryItem]? {
[Optional]
String extension으로 구현하는 게 더 역할에 맞을 것 같아요

2023-08-16 05:37 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/Loading.swift
> +    @State private var progress = Double(0)
넵 어차피 로딩이 끝나면 로딩창이 사라져서 애니메이션을 보여줄 수 없습니다.
만약 Binding을 사용하여 부모 뷰에서 렌더링 여부를 제어하지 않고 자식뷰에서 렌더링 여부를 결정하게 만들면 로딩이 끝나고 애니메이션을 보여준 후 로딩창을 사라지게 만드는 것이 가능하지만, 저번에 Binding들을 제거하면서 그 부분은 뺐습니다.

그렇다고 Loaindg 뷰를 보여주고 progress를 바로 100%까지 채우면 아직 로딩은 안 되었는데 애니메이션만 100%라고 나와버리기 때문에 25%까지 채우고 로딩이 끝나면 바로 로딩뷰를 사라지게 만들었습니다.

이 부분을 로딩이 안 되었어도 바로 100%까지 채우는것으로 변경할까요??

2023-08-16 05:41 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/SendMessage.swift
> +@available(iOS 15.0, *)
[2366e62](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/2366e6268c9fe45d99c2e93cf15b15ee6767e717)

2023-08-16 05:47 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/HomeView.swift
> +    private func parseQueryItems() -> [URLQueryItem]? {
[c1c1c10](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/c1c1c10a635133738d9b170a8b4117ef61382419)

2023-08-16 05:51 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/HomeView.swift
> +    private func parseQueryItems() -> [URLQueryItem]? {
[8fbc678](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/8fbc678f46a17b4a5c0369e2f23446e9334f7e7d)

2023-08-16 07:37 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/ProgressBar.swift
> +                    .offset(x: min(geo.size.width, geo.size.width * progress) - 10, y: 0)
[fadb4fb](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/fadb4fb2c7f3b5926103325d5b4667f438bbbd1f)

Rectangle과 Image를 묶을 방법은 찾지 못했습니다 ㅜㅜ  
배경이 되는 Rectangle과 로딩바가 되는 Rectangle이 ZStack 위에서 겹쳐야 하기 때문입니다.
만약에 Rectangle과 Image를 따로 하나의 스택으로 묶으면 로딩창과 로딩창의 배경이 어긋나게 됩니다. (아래처럼)<br>
<img width="334" alt="스크린샷 2023-08-16 16 36 07" src="https://github.com/pagecall/pagecall-ios-sdk/assets/106307725/6e4f58d8-927f-4239-a0b5-510ae45092c3">
그래서 일단은 바로 Rectangle과 Image가 바로 위아래로 보여 비교될 수 있게 순서를 조정했습니다.

2023-08-16 07:38 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Helpers/ProgressBar.swift
> +                    .offset(x: min(geo.size.width, geo.size.width * progress) - 10, y: 0)
하나로 스택으로 묶더라도 align을 잘 조절해보시면 되지 않을까요??

2023-08-16 07:47 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Helpers/ProgressBar.swift
> +                    .offset(x: min(geo.size.width, geo.size.width * progress) - 10, y: 0)
[134176c](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/134176c551895cf8b4596d114dfe20b28b2b0549)

오 다시시도해보니 되긴 했습니다.. 근데 원래 제리가 요청하셨던게 이런 것인지는 잘 모르겠습니다 ㅜ

2023-08-16 10:07 UTC, qqq1130 commented
@js-seo 수정사항 반영했습니다.

2023-08-17 01:23 UTC, js-seo approved these changes

2023-08-17 01:23 UTC, js-seo commented on examples/swiftui/SwiftUI Example/Extensions/String+parseQueryItems.swift
> +//  String+parseQueryItems.swift
[Optional]
파일이름 바꿔주세요!

2023-08-17 01:25 UTC, qqq1130 commented on examples/swiftui/SwiftUI Example/Extensions/String+parseQueryItems.swift
> +//  String+parseQueryItems.swift
@js-seo  
[c4ef3cb](https://github.com/pagecall/pagecall-ios-sdk/pull/51/commits/c4ef3cb14110429583cea43e79a7a90883c40615) 
반영했습니다! 🥲

2023-08-17 01:36 UTC, merged