feat: Added Apple Pencil connection monitoring
pagecall/pagecall-ios-sdk pull request #52
Opened 2023-07-27 10:33 UTC by parkjurung

# Changes
- 3초마다 애플펜슬 연결을 확인하여 연결 상태가 변경될 때 emitter로 전달합니다.

# Test
- info.plist 에 `NSBluetoothAlwaysUsageDescription`가 없더라도 앱이 크래시 나지 않는 것을 확인했습니다.
- info.plist 에 `NSBluetoothAlwaysUsageDescription`가 기재되어 있으면 디버거에서 로그가 잘 보이는 것을 확인했습니다.
<img width="320" alt="Pasted Graphic 76" src="https://github.com/pagecall/pagecall-ios-sdk/assets/19991994/d5c347bb-ccca-46ee-b1ed-3a82851a5e18">

2023-07-28 01:29 UTC, qqq1130 submitted a review, later dismissed

2023-08-01 04:14 UTC, js-seo requested changes

2023-08-01 04:14 UTC, js-seo commented on Sources/PagecallSDK/NativeBridge.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(self.applePencilConnectionChanged(notification:)), name: .applePencilConnectionChanged, object: nil)
[Minor]
removeObserver를 안해주더라도 문제없을까요?
웹뷰를 닫았을 때 올바르게 메모리에서 정리되는지 (사파리 디버거에서 웹뷰가 더 이상 나타나지 않는지) 확인이 필요할 것 같습니다!

2023-08-01 04:14 UTC, js-seo commented on Sources/PagecallSDK/ApplePencilMonitor.swift
> +        self.timer = Timer.scheduledTimer(withTimeInterval: 3.0, repeats: true) { timer in
[Minor]
Polling을 안하는 방법은 없을까요? 무거운 동작은 아니지만 불가피한 경우가 아니면 피하는 게 좋을 것 같습니다

2023-08-01 04:14 UTC, js-seo commented on Sources/PagecallSDK/ApplePencilMonitor.swift
> +                        NotificationCenter.default.post(name: .applePencilConnectionChanged, object: nil, userInfo: ["connected": true])
[Minor]
현시점에 전역적으로 필요한 알림이 아니라 부모인 NativeBridge 에게만 전달되면 되는 것이라,
delegate 패턴을 쓰는게 더 좋을 것 같습니다!
참고: https://velog.io/@nala/iOS-Delegate-%ED%8C%A8%ED%84%B4%EC%9D%84-%EC%9D%B4%ED%95%B4%ED%95%B4%EB%B3%B4%EC%9E%90

2023-08-01 04:22 UTC, parkjurung commented on Sources/PagecallSDK/ApplePencilMonitor.swift
> +        self.timer = Timer.scheduledTimer(withTimeInterval: 3.0, repeats: true) { timer in
블루투스 장치가 변경될때마다 불리는 이벤트가 있긴 했습니다. 그런데 실험해보니 치명적인 한계점이 있었습니다. 그것은 바로 애플펜슬이 다른 기기에 연결되었을때 그 이벤트 발화가 안됩니다. 그래서 일반적으로 사용하는 방법을 찾아보았고 이 방법이 최선인 것으로 판단했습니다.

2023-08-01 04:22 UTC, parkjurung commented on Sources/PagecallSDK/NativeBridge.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(self.applePencilConnectionChanged(notification:)), name: .applePencilConnectionChanged, object: nil)
remove 필요합니다! 대응하겠습니다.

2023-08-01 04:22 UTC, parkjurung commented on Sources/PagecallSDK/ApplePencilMonitor.swift
> +                        NotificationCenter.default.post(name: .applePencilConnectionChanged, object: nil, userInfo: ["connected": true])
delegate 패턴으로 변경하겠습니다.

2023-08-04 05:37 UTC, parkjurung commented
항상 해당 모니터링이 활성화 되어있을때의 부작용을 예상하기 어려워서 pointer debug 할때 처럼 코어앱의 특정 플래그에 따라 선택적으로 활성화되도록 하겠습니다. 우선 해당 PR은 닫겠습니다.

2023-08-04 05:37 UTC, closed without merging