fix: use audioRecorder on demand
pagecall/pagecall-ios-sdk pull request #7
Opened 2023-01-13 07:38 UTC by parkjurung

기존에는 audioRecorder.record() 가 ChimeController init 할때 미리 불리고 있었습니다.
PagecallWebView를 Pagecall room을 표시할때만 이용하는 사례에서는 문제가 없으나 일부 PagecallWebView를 Pagecall 이외의 목적으로도 사용하는 케이스에서 보안 이슈 및 부작용이 있을 수 있습니다.
따라서 audioRecorder.record() 를 꼭 필요할 때만 호출하도록 변경하였습니다.

2023-01-15 08:47 UTC, js-seo requested changes

2023-01-15 08:47 UTC, js-seo commented on Sources/PagecallSDK/ChimeController.swift
> +            audioRecorder.record()
생성한 직후에도 60-63줄에 해당하는 작업을 동일하게 해주세요
지금은 requestAudioVolume을 한번만 호출했을 때는 콜백이 오지 않고 두번째부터 오게 되기 때문입니다

2023-01-15 08:55 UTC, parkjurung commented on Sources/PagecallSDK/ChimeController.swift
> +            audioRecorder.record()
[6467f03](https://github.com/pagecall/pagecall-ios-sdk/pull/7/commits/6467f035ddeeb8826dcaffca9503873dde3a243e) 여기서 해결하였습니다!

2023-01-15 09:08 UTC, js-seo approved these changes

2023-01-16 03:02 UTC, lockcept approved these changes

2023-01-16 06:55 UTC, merged